apiVersion: v1
kind: ServiceAccount
metadata:
  name: api1
  labels:
    authz-opa-istio-injection: "enabled"
    authz-handler: "enabled"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api1
  labels:
    authz-opa-istio: "enabled"
  annotations:
    opaconfig: "opaconfig1"
    authzrun: "1"
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: api
      api: api1
      version: v1
  template:
    metadata:
      labels:
        app: api
        api: api1
        version: v1
        authz-opa-istio: "enabled"
    spec:
      serviceAccountName: api1
      containers:
        - image: daime/http-dump
          imagePullPolicy: IfNotPresent
          name: api1
          ports:
            - containerPort: 80
          env:
            - name: PORT
              value: "80"
---
apiVersion: v1
kind: Service
metadata:
  name: api1
  labels:
    app: api
    api: api1
    service: api1
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: api
    api: api1