apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-istio-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/yerinu2019/cicd.git
    targetRevision: HEAD
    path: argocd/applications/argocd-istio-app

  destination:
    namespace: production  #  ???
    server: {{ .Values.spec.destination.server }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true