apiVersion: v1
kind: ServiceAccount
metadata:
  name: authz-operator
  annotations:
    argocd.argoproj.io/sync-wave: "1"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: authz-operator
  annotations:
    argocd.argoproj.io/sync-wave: "2"
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: authz-operator   # authz-operator has permission to grant clusterroles to service accounts
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authz-operator
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  selector:
    matchLabels:
      app: authz-operator
  replicas: 1
  template:
    metadata:
      labels:
        app: authz-operator
    spec:
      containers:
        - name: authz-operator
          image: yerinu2019/authz-operator:latest
          imagePullPolicy: Always
          args:
            - "--log-level=debug"
      serviceAccountName: authz-operator