apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: opaconfigs.example.com
  namespace: opa-istio
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: example.com
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1alpha1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                rego-bundle-url:
                  description: Storage URL, e.g. Google Cloud Storage bucket url, where OPA rego bundle file is stored.
                  type: string
                rego-bundle-file:
                  description: OPA rego bundle file name
                  type: string
                kube-mgmt-replicate:
                  description: Kubernetes resource types that kube-mgmt replicate to OPA envoy plugin
                  type: string
                policy-crd-name:
                  description: Authz policy CRD name
                  type: string
                policy-crd-version:
                  description: Authz policy CRD version
                  type: string
                policy-crd-group:
                  description: Authz policy CRD group
                  type: string
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: opaconfigs
    # singular name to be used as an alias on the CLI and for display
    singular: opaconfig
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: OpaConfig
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
      - opaconf