apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  namespace: argocd
commonAnnotations:
  external-dns.alpha.kubernetes.io/hostname: argocd.svc.yerinu.com.
patchesJson6902:
  - target:
      version: v1
      kind: Service
      namespace: argocd
      name: argocd-server
    patch: |-
      - op: replace
        path: /spec/type
        value: LoadBalancer