apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: authz-opa-istio
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: "gke_monorepotest-323514_us-central1-a_cluster1"
            cluster-name: "gke-monorepotest-cluster1"
  template:
    metadata:
      name: 'authz-opa-istio-{{cluster-name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/yerinu2019/cicd.git
        targetRevision: HEAD
        path: authz/graphql/opa-istio
      destination:
        name: "{{cluster}}"
        namespace: opa-istio
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - CreateNamespace=true