apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: authz-acl
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: gke_monorepotest-323514_us-central1-a_cluster1
            namespace: api-istio
  template:
    metadata:
      name: 'authz-acl-{{cluster}}-{{namespace}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/yerinu2019/cicd.git
        targetRevision: HEAD
        path: authz/graphql/acl
        directory:
          recurse: true
      destination:
        name: {{cluster}}
        namespace: {{namespace}}
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - CreateNamespace=true