apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authz-namespace
  namespace: argocd
  finalizers:
spec:
  project: default
  source:
    repoURL: https://github.com/yerinu2019/cicd.git
    targetRevision: HEAD
    path: authz/graphql/namespace
    directory:
      recurse: true
  destination:
    namespace: api-istio
    # Uncomment name to deploy api-istio namespace resources to cluster1
    name: gke_monorepotest-323514_us-central1-a_cluster1
    #server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true