apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: opa-envoy-plugin-git
spec:
  type: git
  params:
    - name: revision
      value: main
    - name: url
      value: https://github.com/yerinu2019/opa-envoy-plugin #configure: change if you want to build something else, perhaps from your own local git repository.