apiVersion: v1
kind: ServiceAccount
metadata:
  name: dockerhub-sa
secrets:
  - name: dockerhub-credential
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: build-and-push
spec:
  serviceAccountName: dockerhub-sa
  taskRef:
    name: build-and-push
  workspaces:
    - name: kaniko
      persistentVolumeClaim:
        claimName: dockerfile-claim