apiVersion: v1
kind: ServiceAccount
metadata:
  name: dockerhub-sa
secrets:
  - name: dockerhub-credential
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dockerfile
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  hostPath:
    path: /home/docker/kaniko # replace with local directory, such as "/home/<user-name>/kaniko"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dockerfile-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: local-storage
---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: build-and-push
spec:
  serviceAccountName: dockerhub-sa
  taskRef:
    name: build-and-push
  workspaces:
    - name: kaniko
      persistentVolumeClaim:
        claimName: dockerfile-claim