apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  namespace: tekton-pipelines
resources:
  - dashboard.yaml
commonAnnotations:
  external-dns.alpha.kubernetes.io/hostname: tekton.svc.yerinu.com.
patchesJson6902:
  - target:
      version: v1
      kind: Service
      namespace: tekton-pipelines
      name: tekton-dashboard
    patch: |-
      - op: replace
        path: /spec/type
        value: NodePort
