apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tekton-pipelines
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Service
    metadata:
      name: tekton-dashboard
    spec:
      type: LoadBalancer
      ports:
        - port: 9097
          targetPort: 80