apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  namespace: tekton-pipelines
resources:
  - dashboard.yaml
patches:
  - patch: patch.yaml
    target:
      kind: Service
      namespace: tekton-pipelines
      name: tekton-dashboard
