apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  namespace: tekton-pipelines
resources:
  - dashboard.yaml
#target:
#  kind: Service
#  namespace: tekton-pipelines
#  name: tekton-dashboard
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Service
    metadata:
      name: tekton-dashboard
      namespace: tekton-pipelines
    spec:
      type: LoadBalancer
      ports:
        - name: http
          port: 80
          targetPort: 9097
