apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  namespace: api-istio
resources:
  - opa-envoy-filter.yaml
  - opa-rbac.yaml
  - opa-istio.yaml
  - gcs-egress.yaml
  - rego-configmap.yaml