apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authz
  finalizers:

spec:
  project: default
  source:
    repoURL: https://github.com/yerinu2019/authz.git
    targetRevision: HEAD
    path: simulation/single-cluster/minikube/policy/crd
    directory:
      recurse: true
  destination:
    namespace: api-istio
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true