apiVersion: apps/v1
kind: Deployment
metadata:
  name: authz-operator
  namespace: api-istio
spec:
  selector:
    matchLabels:
      app: authz-operator
  replicas: 1
  template:
    metadata:
      labels:
        app: authz-operator
    spec:
      containers:
        - name: authz-operator
          image: yerinu2019/authz-operator:latest
          imagePullPolicy: Always