apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: authz-operator-api-istio
  annotations:
    argocd.argoproj.io/sync-wave: "2"
roleRef:
  kind: ClusterRole
  name: authz-operator
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: Group
    name: system:serviceaccounts:api-istio
    apiGroup: rbac.authorization.k8s.io
  - kind: ServiceAccount
    name: default
    namespace: api-istio
---
