apiVersion: v1
kind: Deployment
metadata:
  name: authz-operator
  namespace: api-istio
spec:
  replicas: 1
  template:
    containers:
      - name: authz-operator
        image: yerinu2019/authz-operator:latest
        imagePullPolicy: Always