apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: api-istio
  name: authz-operator-admin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: authz-operator-admin
  annotations:
    argocd.argoproj.io/sync-wave: "2"
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: authz-operator-admin   # authz-operator-admin has permission to grant clusterroles to service accounts
    namespace: api-istio