apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authz-opa-istio
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yerinu2019/cicd.git
    targetRevision: HEAD
    path: authz/graphql/opa-istio
  destination:
    namespace: opa-istio
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true