apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: argo-events
  name: argo-event-handler-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-event-handler-role
  namespace: argo-events
rules:
  - apiGroups:
      - argoproj.io
    verbs:
      - "*"
    resources:
      - clusterrolebindings
      - rolebindings
      - serviceaccounts
      - workflows
      - workflowtemplates
      - cronworkflows
      - clusterworkflowtemplates
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-event-handler-role-binding
  namespace: argo-events
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-event-handler-role
subjects:
  - kind: ServiceAccount
    name: argo-event-handler-sa