apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: argo-events
  # service account that can automatically create or delete service account and bind clusterrole in namespace
  name: argo-event-clusterrole-binder-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-event-clusterrole-binder-role
  namespace: argo-events
rules:
  - apiGroups:
      - ""
    verbs:
      - "*"
    resources:
      - clusterrolebindings
      - serviceaccounts
  - apiGroups:
      - ""
    verbs:
      - get
      - list
      - watch
    resources:
      - namespaces

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-event-clusterrole-binder-binding
  namespace: argo-events
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-event-clusterrole-binder-role
subjects:
  - kind: ServiceAccount
    name: argo-event-clusterrole-binder-sa